import { Inter } from "next/font/google";
import ContextProvider from "./ContextProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import LayoutProvider from "./LayoutProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Evergreen City Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon.png" />
        <meta name="theme-color" content="#FFFFFF" />
        <meta
          name="description"
          content="Income Expense Tracker for Evergreen City"
        />
      </head>
      <body className={inter.className}>
        <ContextProvider>
          <LayoutProvider>{children}</LayoutProvider>
        </ContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
